### PR TITLE
Facebook service tests

### PR DESCRIPTION
**Pull request by jmerle**
Part of #6 

Also moved the `result` object to the function to prevent future function calls from being messed up by previous function calls.

### CODE REVIEW

**Comment by punit1108** [comment]
Hi @jmerle ,

1. The test cases look good, but can we NOT original services?
2. Can you remove the github test file from your fork just in order to avoid any merge conflicts. :)

**Comment by jmerle** [comment]
What you mean with original services?

The Github file should not create merge conflicts, but I'll remove it just to be sure.

**Comment by punit1108** [comment]
@jmerle I mean can you not change the code in facebook.service.js ?

**Comment by jmerle** [comment]
The code had a bug, that's why I changed it.

Consider the following (with the old code):
1. upstate.facebook() is called when the Facebook service is healthy. result.status would be set to `true`.
2. upstate.facebook() is called a few minutes later, and suddenly Facebook's API indicates status problems. This is where the bug appears: the callback will be called and status will be `true`, instead of the `false` it should return since Facebook has problems. This problem occurs since the result object isn't bound to a specific function call, but rather to all calls to upstate.facebook().

**Comment by punit1108** [comment]
@jmerle 
Thanks for the heads up, it really is a bug. Still what we can do is, just make a new Issue and let the file remain unchanged in this PR. This way we will be able to make and track the changed (your suggested changes) in all the service functions (ie, github.service, facebook.service, heroku.service).

**Comment by jmerle** [comment]
Sure, I'll remove it from this PR and create a new PR to fix all the 3 services with the issue at once.

**Comment by punit1108** [comment]
Hi @jmerle , can you update this PR so that the Test cases pass and we can merge this PR?

**Pull request merged**
